name: dynamic_key_logic_key_locking
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.12
  - pip
  - pip:
      - alabaster==0.7.12
      - asttokens==2.4.1
      - Babel==2.8.0
      - beautifulsoup4==4.10.0
      - blinker==1.4
      - certifi==2020.6.20
      - chardet==4.0.0
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.2.1
      - cryptography==3.4.8
      - cycler==0.12.1
      - Cython==3.0.8
      - debugpy==1.8.1
      - decorator==5.1.1
      - docutils==0.17.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fonttools==4.53.1
      - gcovr==5.0
      - html5lib==1.1
      - httplib2==0.20.2
      - idna==3.3
      - imagesize==1.3.0
      - importlib-metadata==4.6.4
      - ipykernel==6.29.4
      - ipython==8.23.0
      - jedi==0.19.1
      - jeepney==0.7.1
      - Jinja2==3.1.3
      - joblib==1.4.2
      - jupyter_client==8.6.1
      - jupyter_core==5.7.2
      - keyring==23.5.0
      - kiwisolver==1.4.5
      - launchpadlib==1.10.16
      - lazr.restfulclient==0.14.4
      - lazr.uri==1.0.6
      - lxml==4.8.0
      - MarkupSafe==2.1.5
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.6
      - more-itertools==8.10.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - netifaces==0.11.0
      - numpy==2.0.0
      - oauthlib==3.2.0
      - olefile==0.46
      - openpyxl==3.1.5
      - packaging==24.0
      - pandas==2.2.2
      - parso==0.8.3
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.2.0
      - ply==3.11
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pybind11==2.9.1
      - pycairo==1.20.1
      - pyeda==0.29.0
      - Pygments==2.11.2
      - PyGObject==3.42.1
      - PyJWT==2.3.0
      - pyLingeling
      - pyparsing==2.4.7
      # - pyPicosat==965.2407290305
      - PySMT==0.9.5
      - python-dateutil==2.9.0.post0
      - python-resources==0.3
      - pytz==2024.1
      - pyverilog==1.3.0
      - PyYAML==5.4.1
      - pyzmq==25.1.2
      - requests==2.25.1
      - roman==3.3
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - seaborn==0.13.2
      - SecretStorage==3.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.3.1
      - Sphinx==4.3.2
      - sphinx-rtd-theme==1.0.0
      - stack-data==0.6.3
      - threadpoolctl==3.5.0
      - tornado==6.4
      - traitlets==5.14.2
      - typing_extensions==4.10.0
      - tzdata==2024.1
      - urllib3==1.26.5
      - wadllib==1.3.6
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - xdot==1.2
      - zipp==1.0.0
